theme: jekyll-theme-midnight
title: Foundation of Bioinformatics Spring 2018
description: A demo site of students cool class work profiles
logo: https://bioboot.github.io/bggn213_S18/assets/img/logo.png
